packages:
  darwin:
    brews:
      - "argo"
      - "autojump"
      - "awscli"
      - "buf"
      - "chezmoi"
      - "cloc"
      - "datawire/blackbird/telepresence"
      - "fzf"
      - "git"
      - "git-lfs"
      - "gh"
      - "go"
      - "golangci-lint"
      - "goreleaser"
      - "goreman"
      - "gpg"
      - "helm"
      - "htop"
      - "httpie"
      - "int128/kubelogin/kubelogin"
      - "java"
      - "jq"
      - "jsonnet"
      - "jsonnet-bundler"
      - "k3d"
      - "k9s"
      - "kind"
      - "kubectx"
      - "kubernetes-cli"
      - "kustomize"
      - "make"
      - "node"
      - "openjdk"
      - "pnpm"
      - "poetry"
      - "postgresql"
      - "protobuf"
      - "ripgrep"
      - "skaffold"
      - "sops"
      - "tanka"
      - "terraform"
      - "tmux"
      - "v2ray"
      - "vim"
      - "watch"
      - "wget"
      - "yq"
      - "ytt"
      - "zsh-syntax-highlighting"
    casks: []
